import os
print(os.getcwd())
os.chdir("G:/udemy pithon")
print(os.getcwd())
os.chdir("G:/")
print(os.getcwd())
print(os.listdir())
#os.mkdir("rakademo")
print(os.listdir())
print("\n")
#os.makedirs("rakademo/rakademo2/rakademo3")
print(os.listdir())
print("\n")
#os.rmdir("rakademo/rakademo2/rakademo3")
print(os.listdir())
os.makedirs("rakademo/rakademo2/rakademo3")
os.removedirs("rakademo/rakademo2/rakademo3")
print(os.listdir())